version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          working-directory: Cypress
          cypress-command: npx cypress run --browser chrome
          start-command: 'npm run start'
