version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          working-directory: Cypress-Test
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --browser chrome'
          
